name: Build plugin container

on:
  push:
    branches:
      - main
      - testing
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: roydanenterprises/Roydan.DevOps/.github/workflows/build-nextask-plugin.yml@master
    secrets: inherit
